#define INETD_MODE 0

#define DROPBEAR_SMALL_CODE 0

#define ENABLE_CLI_NETCAT 0

#define DROPBEAR_TWOFISH256 0
#define DROPBEAR_TWOFISH128 0

#define DROPBEAR_DELAY_HOSTKEY 0

#define DROPBEAR_CURVE25519 0

#define DO_HOST_LOOKUP 0

#define DO_MOTD 0

#define ENABLE_SVR_PAM_AUTH 0

#define MAX_UNAUTH_PER_IP 3

#define MAX_UNAUTH_CLIENTS 10

#define MAX_AUTH_TRIES 4
